import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <main className="max-w-7xl mx-auto p-4">
          <Header />
          {children}
          <footer className="text-center text-gray-500 border p-8 mt-16">
            &copy; 2024 Todos os direitos reservados
          </footer>
        </main>
      </body>
    </html>
  );
}
